drop table if exists member CASCADE;
create table member
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

-- 삽입
insert into member(name)
values ('spring')

-- 모두 삭제
delete
from member